spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: mesha@gmail.com
    password: 1234
    properties:
      mail:
        smtp:
          trust: "*"
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: QPuOccnNrLk1ki1nco+6oYJiMNPBovmCm/bnPbRoUo5BwblPeKboP0AOKs/+lpTF
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088
